name: build
on:
  schedule: [ cron: "42 13 23 * *" ]
  push: { branches: [ master ] }
  workflow_dispatch:

env:
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2
    - name: timestamp
      run: echo "BUILD_DATE=$(date --iso-8601)" >> $GITHUB_ENV
    - name: docker login
      uses: ./.github/actions/docker-login
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        secret: ${{ secrets.DOCKER_HUB_SECRET }}
    - name: amqp
      uses: ./.github/actions/build
      with:
        image: amqp
        timestamp: ${{ env.BUILD_DATE }}
    - name: aws
      uses: ./.github/actions/build
      with:
        image: aws
        timestamp: ${{ env.BUILD_DATE }}
    - name: buildah
      uses: ./.github/actions/build
      with:
        image: buildah
        timestamp: ${{ env.BUILD_DATE }}
    - name: curl
      uses: ./.github/actions/build
      with:
        image: curl
        timestamp: ${{ env.BUILD_DATE }}
    - name: dig
      uses: ./.github/actions/build
      with:
        image: dig
        timestamp: ${{ env.BUILD_DATE }}
    - name: drill
      uses: ./.github/actions/build
      with:
        image: drill
        timestamp: ${{ env.BUILD_DATE }}
    - name: jq
      uses: ./.github/actions/build
      with:
        image: jq
        timestamp: ${{ env.BUILD_DATE }}
    - name: kubectl
      uses: ./.github/actions/build
      with:
        image: kubectl
        timestamp: ${{ env.BUILD_DATE }}
    - name: mustache
      uses: ./.github/actions/build
      with:
        image: mustache
        timestamp: ${{ env.BUILD_DATE }}
    - name: netcat
      uses: ./.github/actions/build
      with:
        image: netcat
        timestamp: ${{ env.BUILD_DATE }}
    - name: nodejs
      uses: ./.github/actions/build
      with:
        image: nodejs
        timestamp: ${{ env.BUILD_DATE }}
    - name: oathtool
      uses: ./.github/actions/build
      with:
        image: oathtool
        timestamp: ${{ env.BUILD_DATE }}
    - name: podman
      uses: ./.github/actions/build
      with:
        image: podman
        timestamp: ${{ env.BUILD_DATE }}
    - name: socat
      uses: ./.github/actions/build
      with:
        image: socat
        timestamp: ${{ env.BUILD_DATE }}
    - name: syslog-ng
      uses: ./.github/actions/build
      with:
        image: syslog-ng
        timestamp: ${{ env.BUILD_DATE }}
    - name: tinyproxy
      uses: ./.github/actions/build
      with:
        image: tinyproxy
        timestamp: ${{ env.BUILD_DATE }}
    - name: tinydns
      uses: ./.github/actions/build
      with:
        image: tinydns
        timestamp: ${{ env.BUILD_DATE }}
    - name: xml-json
      uses: ./.github/actions/build
      with:
        image: xml-json
        timestamp: ${{ env.BUILD_DATE }}
    - name: docker logout
      if: ${{ always() }}
      uses: ./.github/actions/docker-logout
