name: build
on:
  schedule: [ cron: "42 13 23 * *" ]
  push: { branches: [ master ] }
  workflow_dispatch:

env:
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2
    - name: timestamp
      run: echo "BUILD_DATE=$(date --iso-8601)" >> $GITHUB_ENV
    - name: docker login
      uses: ./.github/actions/docker-login
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        secret: ${{ secrets.DOCKER_HUB_SECRET }}
    - name: amqp
      uses: ./.github/actions/build
      with:
        image: amqp
        timestamp: ${{ env.BUILD_DATE }}
    - name: aws
      uses: ./.github/actions/build
      with:
        image: aws
        timestamp: ${{ env.BUILD_DATE }}
    - name: buildah
      uses: ./.github/actions/build
      with:
        image: buildah
        timestamp: ${{ env.BUILD_DATE }}
    - name: curl
      uses: ./.github/actions/build
      with:
        image: curl
        timestamp: ${{ env.BUILD_DATE }}
    - name: docker logout
      if: ${{ always() }}
      uses: ./.github/actions/docker-logout
