name: build
on:
  schedule: [ cron: "42 13 23 * *" ]
  push:
    branches:
    - master
  workflow_dispatch:

env:
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2
    - name: amqp
      run: |
        cd amqp
        make
        <<<"$REGISTRY_SECRET" buildah login --username="$REGISTRY_USERNAME" --password-stdin "$REGISTRY"
        make push
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        REGISTRY_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
    - name: buildah logout
      if: ${{ always() }}
      run: buildah logout "$REGISTRY"
