name: build
on:
  schedule: [ cron: "42 13 23 * *" ]
  push: { branches: [ master ] }
  workflow_dispatch:

env:
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
    - uses: actions/checkout@v2
    - name: timestamp
      run: echo "BUILD_DATE=$(date --iso-8601)" >> $GITHUB_ENV
    - name: buildah login
      env:
        REGISTRY_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        REGISTRY_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
      run: <<<"$REGISTRY_SECRET" buildah login --username="$REGISTRY_USERNAME" --password-stdin "$REGISTRY"
    - name: amqp
      run: |
        cd amqp
        make
        make push tag="$BUILD_DATE"
        make push
    - name: buildah logout
      if: ${{ always() }}
      run: buildah logout "$REGISTRY"
